In [94]:
import numpy as np

In [95]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1


array([[1, 2, 3],
       [4, 5, 6]])

In [96]:
arr1.shape

(2, 3)

In [97]:
arr2 = np.array([[10,11,12],[13,14,15]])
arr2


array([[10, 11, 12],
       [13, 14, 15]])

In [98]:
arr2.shape

(2, 3)

In [99]:
arr1 + arr2

array([[11, 13, 15],
       [17, 19, 21]])

In [100]:
arr1 * arr2


array([[10, 22, 36],
       [52, 70, 90]])

In [101]:
data = np.random.randn(8,4)
data

array([[-0.43444052, -0.09857578, -1.54957637,  0.02195734],
       [ 0.35150374, -1.02826014, -0.11562379,  0.18918977],
       [ 0.23087649, -0.99885613,  0.01694067, -2.21468869],
       [-0.07160481,  0.15997216,  1.82895542,  0.85099352],
       [ 0.89760273,  0.98951602,  0.66984218,  0.50701045],
       [-3.00516828, -1.48174206, -1.09668982, -1.16486313],
       [ 0.86901166,  0.75211413,  0.58535116, -0.75699982],
       [-1.82925904,  0.52294636,  0.88561413,  0.05889489]])

In [102]:
data.shape

(8, 4)

In [103]:
names = np.array(['Beomwoo','Beomwoo','Kim','Joan','Lee','Beomwoo','Park','Beomwoo'])
names


array(['Beomwoo', 'Beomwoo', 'Kim', 'Joan', 'Lee', 'Beomwoo', 'Park',
       'Beomwoo'], dtype='<U7')

In [104]:
data[names == 'Kim',:]

array([[ 0.23087649, -0.99885613,  0.01694067, -2.21468869]])

In [105]:
data[:,0] < 0

array([ True, False, False,  True, False,  True, False,  True])

In [107]:
arr2[arr2 >7] 

array([10, 11, 12, 13, 14, 15])

arr4 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr4


data2 = [4,5,6]
data2